const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const fmt=value=>Number(value).toLocaleString('zh-CN');
const pct=value=>`${Number(value).toFixed(1)}%`;
const typeOrder=['品牌认知型','品牌对比型','业务场景型'];
const sourceLabels={official_direct:'官方直引',associated_product:'关联产品',platform_official:'平台官方',competitor:'竞品',media:'媒体',community:'社区',other:'其他'};
const qualityLabels={pass:'通过',fail:'不通过',unknown:'未知'};
let DATA,currentType='品牌认知型',page=1;
function card(label,value,meta,rule,color=''){return `<article class="kpi"><div class="kpi-label">${esc(label)}<span class="info" tabindex="0">!<span>${esc(rule)}</span></span></div><strong class="kpi-value ${color}">${esc(value)}</strong><div class="kpi-meta">${esc(meta)}</div></article>`}
function currentRows(){return DATA.citations.filter(row=>row.questionType===currentType)}
function renderSummary(){const group=DATA.groups[currentType];document.getElementById('metric-grid').innerHTML=[card('回答引用覆盖率',pct(group.coveragePercentage),`${group.citedSamples} / ${group.sampleCount} 个回答`,'含至少 1 个规范化引用 URL 的回答数 / 本问题类型引用状态已确认回答数。','orange'),card('引用记录',fmt(group.citationRows),'同一样本内 URL 去重','每行对应一个样本内去重后的引用 URL。'),card('唯一网址',fmt(group.uniqueUrls),'跨回答按规范 URL 去重','当前问题类型全部引用按规范 URL 去重。'),card('来源网站',fmt(group.uniqueDomains),'按精确主机名去重','当前问题类型全部引用按最终域名去重。'),card('明确无引用',fmt(group.confirmedNoCitationSamples),`${group.confirmedNoCitationSamples} / ${group.sampleCount} 个回答`,'采集已成功且确认没有引用的回答，不等于引用采集失败。')].join('');const rows=currentRows(),sourceCounts={},domainCounts={};for(const row of rows){sourceCounts[row.sourceType]=(sourceCounts[row.sourceType]||0)+1;domainCounts[row.domain]=(domainCounts[row.domain]||0)+1}renderBars('source-bars',Object.entries(sourceCounts).sort((a,b)=>b[1]-a[1]).map(([name,count])=>[sourceLabels[name]||name,count]));renderBars('domain-bars',Object.entries(domainCounts).sort((a,b)=>b[1]-a[1]).slice(0,10))}
function renderBars(id,rows){const max=Math.max(1,...rows.map(row=>row[1]));document.getElementById(id).innerHTML=rows.map(([name,count])=>`<div class="bar-row"><span>${esc(name)}</span><span class="bar-track"><span class="bar-fill" style="width:${count/max*100}%"></span></span><span class="bar-value">${fmt(count)}</span></div>`).join('')}
function qualityBadge(label,value){return `<span class="badge ${esc(value)}">${esc(label)}：${esc(qualityLabels[value]||value)}</span>`}
function filtered(){const query=document.getElementById('citation-search').value.trim().toLowerCase(),source=document.getElementById('source-filter').value,quality=document.getElementById('quality-filter').value;return currentRows().filter(row=>source==='all'||row.sourceType===source).filter(row=>quality==='all'||row.relevance===quality).filter(row=>!query||`${row.citationId} ${row.sampleId} ${row.question} ${row.title} ${row.url} ${row.domain}`.toLowerCase().includes(query))}
function renderRows(){const rows=filtered(),size=50,pages=Math.max(1,Math.ceil(rows.length/size));page=Math.min(page,pages);const start=(page-1)*size,visible=rows.slice(start,start+size);document.getElementById('citation-count').textContent=`${fmt(rows.length)} / ${fmt(currentRows().length)} 条引用`;document.getElementById('citation-range').textContent=rows.length?`第 ${start+1}-${Math.min(start+size,rows.length)} 条`:'无匹配结果';document.getElementById('page-label').textContent=`${page} / ${pages}`;document.getElementById('prev').disabled=page<=1;document.getElementById('next').disabled=page>=pages;document.getElementById('citation-body').innerHTML=visible.length?visible.map(row=>`<tr id="${esc(row.citationId)}"><td><b>${esc(row.citationId)}</b><br>${esc(row.question)}</td><td><b>${esc(row.title||'未命名来源')}</b><br><a href="${esc(row.url)}" target="_blank" rel="noopener noreferrer">${esc(row.url)}</a>${row.publishedDate?`<br>发布日期 ${esc(row.publishedDate)}`:''}</td><td>${esc(row.domain)}<br><span class="badge">${esc(sourceLabels[row.sourceType]||row.sourceType)}</span></td><td><div class="list-inline">${qualityBadge('可访问',row.accessibility)}${qualityBadge('权威',row.authority)}${qualityBadge('相关',row.relevance)}${qualityBadge('新鲜',row.freshness)}</div></td></tr>`).join(''):'<tr><td colspan="4" class="empty">当前筛选无引用记录</td></tr>'}
function setType(type){currentType=type;page=1;document.querySelectorAll('#type-tabs button').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.type===type)));const url=new URL(location);url.searchParams.set('type',type);history.replaceState(null,'',url);renderSummary();renderRows()}
async function start(){try{const response=await fetch('./citation-data.json',{cache:'no-store'});if(!response.ok)throw new Error(`HTTP ${response.status}`);DATA=await response.json();const requested=new URLSearchParams(location.search).get('type');if(typeOrder.includes(requested))currentType=requested;document.getElementById('type-tabs').innerHTML=typeOrder.map(type=>`<button type="button" data-type="${type}" aria-pressed="${type===currentType}">${type}</button>`).join('');document.getElementById('type-tabs').addEventListener('click',event=>{const button=event.target.closest('button');if(button)setType(button.dataset.type)});for(const item of DATA.sourceTypes){const option=document.createElement('option');option.value=item.name;option.textContent=sourceLabels[item.name]||item.name;document.getElementById('source-filter').append(option)}for(const id of ['citation-search','source-filter','quality-filter'])document.getElementById(id).addEventListener('input',()=>{page=1;renderRows()});document.getElementById('reset').addEventListener('click',()=>{document.getElementById('citation-search').value='';document.getElementById('source-filter').value='all';document.getElementById('quality-filter').value='all';page=1;renderRows()});document.getElementById('prev').addEventListener('click',()=>{page-=1;renderRows()});document.getElementById('next').addEventListener('click',()=>{page+=1;renderRows()});renderSummary();renderRows()}catch(error){document.getElementById('citation-body').innerHTML='<tr><td colspan="4" class="empty">引用数据加载失败，请刷新页面。</td></tr>';console.error(error)}}
start();
